services:
  - type: web
    name: viral-clip-generator
    env: python
    buildCommand: pip install -r nr1-main/requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 5000
    envVars:
      - key: ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: viral-clips-data
      mountPath: /opt/render/project/src/nr1-main/videos
      sizeGB: 1
